---
apiVersion: v1
kind: Service
metadata:
  name: iot-engine
spec:
  ports:
  - port: 5574
    targetPort: 5574
    protocol: TCP
  type: LoadBalancer
  selector:
    app: iot-engine
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: iot-engine
spec:
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  selector:
    matchLabels:
      app: iot-engine
  template:
    metadata:
      labels:
        app: iot-engine
    spec:
      containers:
      - name: iot-engine
        image: andresgomezfrr/iot-engine:latest
        imagePullPolicy: Always
        env:
        - name: BOOTSTRAP_SERVERS
          value: "kafka-hs:9092"
        - name: APPLICATION_ID
          value: "iot-engine"
        - name: POD_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        - name: REST_SERVER_ENDPOINT
          value: "0.0.0.0:5574"
        - name: APPLICATION_SERVER
          value: "$(POD_IP):5574"
        ports:
        - containerPort: 5574
        readinessProbe:
          initialDelaySeconds: 30
          timeoutSeconds: 5
          periodSeconds: 10
          failureThreshold: 3
          httpGet:
            path: /iot-engine/instances
            port: 5574
        livenessProbe:
          initialDelaySeconds: 30
          timeoutSeconds: 3
          periodSeconds: 10
          failureThreshold: 3
          httpGet:
            path: /iot-engine/instances
            port: 5574
        resources:
          requests:
            memory: "250Mi"
            cpu: "250m"
          limits:
            memory: "500Mi"
            cpu: "500m"
      restartPolicy: Always
---
apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler
metadata:
  name: iot-engine
spec:
  scaleTargetRef:
    apiVersion: apps/v1beta1
    kind: Deployment
    name: iot-engine
  minReplicas: 1
  maxReplicas: 4
  metrics:
  - type: Resource
    resource:
      name: cpu
      targetAverageUtilization: 80
